### ISSUE TITLE
Window is not defined error when using react frameworks

### ISSUE THREAD

**Issue by Lance1997** [nexmo-se/video-express-react-app#96]
I have tried using the setup as is and it works with no issues. 

But when I try to use it in frameworks like Next.JS or Remix run, I get issues with the window object not being defined. I tried to run the code in useEffect hook and also with Next.JS dynamic imports for components with no ssr support but still I have the window undefined error.

I am not sure if it's an issue I should be sharing here, probably should be sharing it in the framework issue but I just wanted to mention and see if there are any possible solutions.

At the moment I am not even able to use any of the hooks from this project that import the VideoExpress package. Once a hook or component uses that package, I get window is undefined error.

Example of the erorr in remix.run

```
ReferenceError: window is not defined
    at Object.<anonymous> (/frontend/node_modules/@vonage/video-express/node_modules/@opentok/client/dist/js/opentok.js:20:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/frontend/node_modules/@vonage/video-express/dist/video-express.cjs.development.js:17:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/frontend/node_modules/@vonage/video-express/dist/index.js:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**Comment by Lance1997** [comment]
With Next.JS I was not able to solve the issue.

With remix run though, the use of their file naming convention `filename.client.ts` allows to run code client side only and so I don't get window undefined error but I get an error specific to remix. Basically remix checks for `"sideEffects": false` from third party packages that are used in the `filename.client.ts` convention to tree shake and safely remove code from browser bundles but it seems the @vonage/video-express package does not have that in it's package.json so remix is not able to do that. 

A suggestion by remix is to submit a PR to the code for the sideffects to be added but since the package is not really open sourced with a repository, I cannot ask for such help or PR.

**Comment by Lance1997** [comment]
I tried patching the package with the "sideEffects": false but that also still failed.

**Comment by Lance1997** [comment]
It now runs for me in Next.JS though, I tried it with dynamic components initially but that did not work and this time I added the property `{ssr: false}` to the dynamic import and that did the trick.
